name: utopia_lints
description: Utopia USS libs - recommended lint rules
version: 0.0.4
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter_lints: ^6.0.0