name: utopia_lints
description: Recommended lint rules for Utopia projects - extends flutter_lints with strict type-checking and a curated set of analyzer rules.
topics:
  - lints
  - linter
  - analysis
  - flutter
  - dart
version: 0.0.5
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter_lints: ^6.0.0