name: utopia_platform_utils
description: Shared Kotlin and Swift base classes for writing Flutter plugins - activity-aware lifecycle and coroutine scopes. No Dart-facing API.
topics:
  - plugin
  - android
  - ios
  - flutter
  - platform-channel
version: 0.0.7
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  utopia_lints: ^0.0.5

flutter:
  plugin:
    platforms:
      android:
        package: com.utopiaultimate.flutter.utopia_platform_utils
        pluginClass: UtopiaPlatformUtilsPlugin
      ios:
        pluginClass: UtopiaPlatformUtilsPlugin
