name: utopia_localization_template
description: Internal shared models for utopia_localization_annotation and utopia_localization_generator - Google Sheets-based i18n/l10n localization code generation.
topics:
  - localization
  - i18n
  - l10n
  - codegen
  - flutter
version: 0.0.3
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  intl: ">= 0.17.0 <1.0.0"
