name: utopia_localization_annotation
description: Localization annotations for utopia_localization_generator - marks classes for Google Sheets-based i18n/l10n code generation in Flutter.
topics:
  - localization
  - i18n
  - l10n
  - codegen
  - flutter
version: 0.0.3+1
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  utopia_localization_template: ^0.0.3
