name: utopia_firebase_crashlytics
description: Utopia USS libs - firebase crashlytics setup and Reporter implementation
version: 0.2.0+6
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_reporter: ^0.1.0+5
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0

dev_dependencies:
  utopia_lints: ^0.0.4