name: utopia_save_file
description: Utopia USS libs - unified and *correct* implementation of file saving
version: 0.2.4+2
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  utopia_utils: ^0.3.3
  utopia_platform_utils: ^0.0.6+1
  path: ^1.8.0
  path_provider: ^2.0.5
  cross_file: ^0.3.3+4
  mime: ^2.0.0
  http: ^1.1.0
  web: ^1.1.0


dev_dependencies:
  utopia_lints: ^0.0.4+1

flutter:
  plugin:
    platforms:
      android:
        package: com.utopiaultimate.flutter.utopia_save_file
        pluginClass: UtopiaSaveFilePlugin
      ios:
        pluginClass: UtopiaSaveFilePlugin
      web:
        pluginClass: UtopiaSaveFilePlugin
        fileName: utopia_save_file_plugin.dart
      macos:
        pluginClass: UtopiaSaveFilePlugin
